// <auto-generated />
using System;
using HelpDesk.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.DataAccess.Migrations
{
    [DbContext(typeof(HelpDeskDbContext))]
    [Migration("20261010143433_FixUserSeedTph")]
    partial class FixUserSeedTph
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Activo = true,
                            Descripcion = "Problemas de hardware",
                            Nombre = "Hardware"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Activo = true,
                            Descripcion = "Problemas de software",
                            Nombre = "Software"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Activo = true,
                            Descripcion = "Problemas de red y conectividad",
                            Nombre = "Red"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Activo = true,
                            Descripcion = "Gestión de accesos y permisos",
                            Nombre = "Accesos"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Activo = true,
                            Descripcion = "Otras consultas",
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsInterno")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Entregada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Usado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Priority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("SLAHoras")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Prioridades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#16A34A",
                            Nivel = 1,
                            Nombre = "Baja",
                            SLAHoras = 72
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "#CA8A04",
                            Nivel = 2,
                            Nombre = "Media",
                            SLAHoras = 24
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Color = "#EA580C",
                            Nivel = 3,
                            Nombre = "Alta",
                            SLAHoras = 8
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Color = "#DC2626",
                            Nivel = 4,
                            Nombre = "Crítica",
                            SLAHoras = 4
                        });
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Solution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ContenidoArchivo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TamanioArchivo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoContenido")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Soluciones");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsFinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Descripcion = "Ticket recién creado",
                            EsFinal = false,
                            Nombre = "Abierto",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Descripcion = "Ticket siendo trabajado",
                            EsFinal = false,
                            Nombre = "En Progreso",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Descripcion = "Ticket resuelto, pendiente de cierre",
                            EsFinal = false,
                            Nombre = "Resuelto",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Descripcion = "Ticket cerrado definitivamente",
                            EsFinal = true,
                            Nombre = "Cerrado",
                            Orden = 4
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Descripcion = "Ticket reabierto después de cerrado",
                            EsFinal = false,
                            Nombre = "Reabierto",
                            Orden = 5
                        },
                        new
                        {
                            Id = new Guid("ffffffff-aaaa-bbbb-cccc-dddddddddddd"),
                            Descripcion = "Ticket escalado por incumplimiento de SLA",
                            EsFinal = false,
                            Nombre = "Escalado",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EstadoAnteriorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EstadoNuevoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrioridadId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TecnicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TeamTecnico", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "TecnicoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("TeamTecnicos", (string)null);
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Empleado", b =>
                {
                    b.HasBaseType("HelpDesk.DataAccess.Entities.User");

                    b.HasDiscriminator().HasValue("Empleado");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Activo = true,
                            Email = "juan.perez@empresa.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Juan Pérez",
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-cccc-dddd-eeee-ffffffffffff"),
                            Activo = true,
                            Email = "maria.garcia@empresa.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "María García",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Supervisor", b =>
                {
                    b.HasBaseType("HelpDesk.DataAccess.Entities.User");

                    b.HasDiscriminator().HasValue("Supervisor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Activo = true,
                            Email = "admin@helpdesk.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Admin Sistema",
                            Rol = 3
                        });
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Tecnico", b =>
                {
                    b.HasBaseType("HelpDesk.DataAccess.Entities.User");

                    b.HasDiscriminator().HasValue("Tecnico");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-dddd-eeee-ffff-aaaaaaaaaaaa"),
                            Activo = true,
                            Email = "carlos.lopez@empresa.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Carlos López",
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("dddddddd-eeee-ffff-aaaa-bbbbbbbbbbbb"),
                            Activo = true,
                            Email = "ana.martinez@empresa.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Ana Martínez",
                            Rol = 2
                        });
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Comment", b =>
                {
                    b.HasOne("HelpDesk.DataAccess.Entities.Ticket", "Ticket")
                        .WithMany("Comentarios")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.User", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Notification", b =>
                {
                    b.HasOne("HelpDesk.DataAccess.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("HelpDesk.DataAccess.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Rating", b =>
                {
                    b.HasOne("HelpDesk.DataAccess.Entities.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("HelpDesk.DataAccess.Entities.Rating", "TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Solution", b =>
                {
                    b.HasOne("HelpDesk.DataAccess.Entities.User", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.User", null)
                        .WithMany("SolucionesRegistradas")
                        .HasForeignKey("UserId");

                    b.Navigation("Tecnico");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.StatusHistory", b =>
                {
                    b.HasOne("HelpDesk.DataAccess.Entities.Status", "EstadoAnterior")
                        .WithMany("HistorialEstadoAnterior")
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpDesk.DataAccess.Entities.Status", "EstadoNuevo")
                        .WithMany("HistorialEstadoNuevo")
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.Ticket", "Ticket")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.User", "Usuario")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Team", b =>
                {
                    b.HasOne("HelpDesk.DataAccess.Entities.Category", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Ticket", b =>
                {
                    b.HasOne("HelpDesk.DataAccess.Entities.Category", "Categoria")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.User", "Empleado")
                        .WithMany("TicketsCreados")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.Status", "Estado")
                        .WithMany("Tickets")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.Priority", "Prioridad")
                        .WithMany("Tickets")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.Team", "Team")
                        .WithMany("Tickets")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HelpDesk.DataAccess.Entities.User", "Tecnico")
                        .WithMany("TicketsAsignados")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Empleado");

                    b.Navigation("Estado");

                    b.Navigation("Prioridad");

                    b.Navigation("Team");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("TeamTecnico", b =>
                {
                    b.HasOne("HelpDesk.DataAccess.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Priority", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Status", b =>
                {
                    b.Navigation("HistorialEstadoAnterior");

                    b.Navigation("HistorialEstadoNuevo");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Team", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.Ticket", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("HelpDesk.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("HistorialEstados");

                    b.Navigation("SolucionesRegistradas");

                    b.Navigation("TicketsAsignados");

                    b.Navigation("TicketsCreados");
                });
#pragma warning restore 612, 618
        }
    }
}
